// Re-export all types from validation package
export type {
  ArrayColumnType,
  CachedTableMeta,
  CacheMeta,
  ColumnFilterOperator,
  ColumnMeta,
  ColumnType,
  CountResult,
  DatabaseEngine,
  DatabaseMeta,
  DataResult,
  DebugLogEntry,
  ExecutionContext,
  ExternalSync,
  FilterOperator,
  HealthCheckResult,
  MetadataConfig,
  QueryAggregation,
  QueryColumnFilter,
  QueryDefinition,
  QueryExistsFilter,
  QueryFilter,
  QueryFilterGroup,
  QueryGroupBy,
  QueryJoin,
  QueryOrderBy,
  QueryResult,
  QueryResultMeta,
  RelationMeta,
  RoleMeta,
  ScalarColumnType,
  SqlResult,
  TableMeta,
  TableRoleAccess,
} from '@mkven/multi-db-validation'
// Public interfaces
export type { CacheProvider, DbExecutor } from './types/interfaces.js'
// IR types (internal)
export type {
  AggregationClause,
  ColumnMapping,
  ColumnRef,
  CorrelatedSubquery,
  HavingBetween,
  HavingGroup,
  HavingNode,
  JoinClause,
  OrderByClause,
  SqlDialect,
  SqlParts,
  TableRef,
  WhereArrayCondition,
  WhereBetween,
  WhereColumnCondition,
  WhereCondition,
  WhereCountedSubquery,
  WhereExists,
  WhereFunction,
  WhereGroup,
  WhereNode,
} from './types/ir.js'
